export const USER_GROUPS_SERVICE = Symbol('USER_GROUPS_SERVICE');

//--- USE CASES ---
export const GET_CURRENT_USER_USER_GROUPS_USE_CASE = Symbol(
  'GET_CURRENT_USER_USER_GROUPS_USE_CASE',
);
export const GET_USER_GROUP_SUBGROUP_INITIAL_FORM_VALUES_USE_CASE = Symbol(
  'GET_USER_GROUP_SUBGROUP_INITIAL_FORM_VALUES_USE_CASE',
);

//--- APPLICATION LAYER ---
export const USER_GROUPS_BY_CONTRACT_ASSEMBLER = Symbol('USER_GROUP_BY_CONTRACT_ASSEMBLER');
