
const STANDARD_TECH_SETUP_HOUR = 11;
const STANDARD_TECH_SETUP_MINUTES = 0;
const STANDARD_TECH_SETUP_DURATION = 15;

export {
    STANDARD_TECH_SETUP_HOUR,
    STANDARD_TECH_SETUP_MINUTES,
    STANDARD_TECH_SETUP_DURATION};