
export const MUSIC_REPERTOIRE_USE_CASES = Symbol('MUSIC_REPERTOIRE_USE_CASES');
export const MUSIC_REPERTOIRE_USE_CASES_FACTORY = Symbol('MUSIC_REPERTOIRE_USE_CASES_FACTORY');
export const CREATE_MUSIC_REPERTOIRE_ENTRY_USE_CASE = Symbol('CREATE_MUSIC_REPERTOIRE_ENTRY_USE_CASE');
export const GET_MUSIC_REPERTOIRE_BY_USER_ID_USE_CASE = Symbol('GET_MUSIC_REPERTOIRE_BY_USER_ID_USE_CASE');




export const MUSIC_VERSIONS_USE_CASES = Symbol('MUSIC_VERSIONS_USE_CASES');
export const MUSIC_VERSIONS_USE_CASES_FACTORY = Symbol('MUSIC_VERSIONS_USE_CASES_FACTORY');


export const MUSIC_REFERENCES_USE_CASES = Symbol('MUSIC_REFERENCES_USE_CASES');
export const MUSIC_REFERENCES_USE_CASES_FACTORY = Symbol('MUSIC_REFERENCES_USE_CASES_FACTORY');


export const MUSIC_LIBRARY_USE_CASES = Symbol('MUSIC_LIBRARY_USE_CASES');
export const MUSIC_LIBRARY_USE_CASES_FACTORY = Symbol('MUSIC_LIBRARY_USE_CASES_FACTORY');
