import type {RouteDef} from "../types/TRouteDef";

/**
 * Creates an Express Router instance using the factory provided in the route definition.
 *
 * This function calls the `factory` method from the given `RouteDef`, passing it the local
 * route context as `{ context }`. It ensures that the returned value is a valid Express `Router`,
 * i.e., it must have a `.use()` method. If not, it throws a descriptive error indicating
 * which route failed.
 *
 * This promotes encapsulation by allowing each route to generate its own sub-router,
 * optionally scoped with local dependencies or configuration via the context.
 *
 * @param input.routeDef - The route definition containing the factory to build the router
 * @param input.routeContext - The scoped context object to inject into the factory
 *
 * @returns An Express `Router` instance generated by the route factory
 *
 * @throws Will throw an error if the factory returns `undefined`, `null`, or an invalid object
 *         that does not implement the `.use()` method (i.e., not an Express router)
 */
export const createRouterFromFactory = (input: { routeDef: RouteDef, routeContext: any }) => {
    const { routeDef, routeContext } = input;

    const router = routeDef.factory({ context: routeContext });

    if (!router || typeof router.use !== 'function') {
        throw new Error(`Factory in route "${routeDef.path}" did not return a valid Router`);
    }
    return router;
};