






// FNS
export const VERIFY_AUTH_TOKEN_FN = Symbol('VERIFY_AUTH_TOKEN_FN');
export const VERIFY_REFRESH_TOKEN_FN = Symbol('VERIFY_REFRESH_TOKEN_FN');


// --- TOKENS ---
export const CORE_REPOSITORIES: symbol = Symbol('CORE_REPOSITORY');
export const REFRESH_TOKEN_REPO = Symbol('REFRESH_TOKEN_REPO');
export const USER_CREDENTIALS_REPO = Symbol('USER_CREDENTIALS_REPO');
export const USER_PROFILE_REPO = Symbol('USER_PROFILE_REPO');
export const USER_PREFERENCES_REPO = Symbol('USER_PREFERENCES_REPO');
export const CONTRACT_REPO = Symbol('CONTRACT_REPO');
export const EVENT_UNIT_REPO = Symbol('EVENT_UNIT_REPO');
export const MUSIC_REFERENCE_REPO = Symbol('MUSIC_REFERENCE_REPO');
export const MUSIC_VERSION_REPO = Symbol('MUSIC_VERSION_REPO');
export const MUSIC_REPERTOIRE_REPO = Symbol('MUSIC_REPERTOIRE_REPO');