// FNS
export const VERIFY_AUTH_TOKEN_FN = Symbol('VERIFY_AUTH_TOKEN_FN');
export const VERIFY_REFRESH_TOKEN_FN = Symbol('VERIFY_REFRESH_TOKEN_FN');

// --- REPOSITORIES TOKENS ---
export const REFRESH_TOKEN_REPO = Symbol('REFRESH_TOKEN_REPO');
export const USER_CREDENTIALS_REPO = Symbol('USER_CREDENTIALS_REPO');
export const USER_PROFILE_REPO = Symbol('USER_PROFILE_REPO');
export const USER_PREFERENCES_REPO = Symbol('USER_PREFERENCES_REPO');
export const GUEST_COMPANY_REPO = Symbol('GUEST_COMPANY_REPO');
export const CONTRACT_REPO = Symbol('CONTRACT_REPO');
export const CONTRACT_READ_REPO = Symbol('CONTRACT_READ_REPO');
export const ADDENDUM_REPO = Symbol('ADDENDUM_REPO');

export const MUSIC_REFERENCE_REPO = Symbol('MUSIC_REFERENCE_REPO');
export const MUSIC_VERSION_REPO = Symbol('MUSIC_VERSION_REPO');
export const MUSIC_REPERTOIRE_REPO = Symbol('MUSIC_REPERTOIRE_REPO');
export const MUSIC_TAB_CONFIGS_REPO = Symbol('MUSIC_TAB_CONFIGS_REPO');
export const REPERTOIRE_ENTRY_AGGREGATE_REPO = Symbol('REPERTOIRE_ENTRY_AGGREGATE_REPO');

export const CONTRACT_SCOPED_GUARD = Symbol('CONTRACT_SCOPED_GUARD');

// PLAYLISTS
export const PLAYLIST_REPO = Symbol('PLAYLIST_REPO');
export const PLAYLIST_TRACK_REPO = Symbol('PLAYLIST_TRACK_REPO');

// SHOWS
export const SHOW_REPO = Symbol('SHOW_REPO');
export const SHOW_SECTION_REPO = Symbol('SHOW_SECTION_REPO');

// PLATFORM CONTRACT
export const PLATFORM_CONTRACT_REPO = Symbol('PLATFORM_CONTRACT_REPO');

// PASSWORD RESET
export const PASSWORD_RESET_TOKEN_REPO = Symbol('PASSWORD_RESET_TOKEN_REPO');

// QUOTA
export const USAGE_COUNTER_REPO = Symbol('USAGE_COUNTER_REPO');

// CREDIT PURCHASES
export const CREDIT_PURCHASE_REPO = Symbol('CREDIT_PURCHASE_REPO');

// ANALYTICS
export const ANALYTICS_EVENT_REPO = Symbol('ANALYTICS_EVENT_REPO');

// CONTRACT DOCUMENTS STORAGE
export const CONTRACT_STORAGE_SERVICE = Symbol('CONTRACT_STORAGE_SERVICE');

// MAILER
export const MAILER_SERVICE = Symbol('MAILER_SERVICE');

// COMPANY
export const COMPANY_REPO = Symbol('COMPANY_REPO');
export const COMPANY_AGGREGATE_REPO = Symbol('COMPANY_AGGREGATE_REPO');
export const ORG_NODE_REPO = Symbol('ORG_NODE_REPO');
export const ORG_MEMBERSHIP_EVENT_REPO = Symbol('ORG_MEMBERSHIP_EVENT_REPO');
/** @deprecated Use ORG_NODE_REPO */
export const CAST_REPO = ORG_NODE_REPO;
/** @deprecated Use ORG_MEMBERSHIP_EVENT_REPO */
export const CAST_MEMBERSHIP_EVENT_REPO = ORG_MEMBERSHIP_EVENT_REPO;
