const STEP_DURATION = 5;
const ONE_MINUTE_IN_MS = 60000;

const STANDARD_TECH_SETUP_HOUR = 11;
const STANDARD_TECH_SETUP_MINUTES = 0;
const STANDARD_TECH_SETUP_DURATION = 15;

export {
    STEP_DURATION,
    ONE_MINUTE_IN_MS,
    STANDARD_TECH_SETUP_HOUR,
    STANDARD_TECH_SETUP_MINUTES,
    STANDARD_TECH_SETUP_DURATION};