import type { IPlaylistSettings } from "./PLAYLIST_SETTINGS_DEFAULT";
import type { ISingersConfig } from "./SINGERS_CONFIG_DEFAULT";
import type { IMusicianConfig } from "./MUSICIAN_CONFIG_DEFAULT";
import type { IAerialConfig } from "./AERIAL_CONFIG_DEFAULT";
import type { IPlaylistSong } from "./PLAYLIST_SONG_DEFAULT";

/**
 * Interface representing a complete playlist, generated by `PlaylistBuilder`.
 */
export interface IPlaylist {
    /** General playlist settings */
    settings: IPlaylistSettings;

    /** List of songs in the playlist */
    songList: IPlaylistSong[];

    /** Configuration of the performers */
    performers: {
        singersConfig: ISingersConfig;
        musiciansConfig: IMusicianConfig;
        aerialConfig: IAerialConfig;
    };
}

/**
 * Interface defining the parameters required to build a playlist.
 */
interface IPlaylistBuilderInput {
    /** Playlist settings */
    playlistSettings: IPlaylistSettings;

    /** Singers configuration */
    singersConfig: ISingersConfig;

    /** Musicians configuration */
    musiciansConfig: IMusicianConfig;

    /** Aerial performance configuration */
    aerialConfig: IAerialConfig;

    /** Default song model */
    playlistSong: IPlaylistSong;
}

/**
 * @class PlaylistBuilder
 *
 * This class constructs a valid musical playlist based on the provided parameters.
 * It generates a list of songs according to `playlistSettings.numberOfSongs`
 * and integrates performer configurations.
 *
 * ### Usage Example:
 *
 * ```typescript
 * const builder = new PlaylistBuilder({
 *     playlistSettings: PLAYLIST_SETTINGS_DEFAULT,
 *     singersConfig: SINGERS_CONFIG_DEFAULT,
 *     musiciansConfig: MUSICIAN_CONFIG_DEFAULT,
 *     aerialConfig: AERIAL_CONFIG_DEFAULT,
 *     playlistSong: PLAYLIST_SONG_DEFAULT,
 * });
 *
 * const playlist = builder.build();
 * console.log(playlist);
 * ```
 */
export class PlaylistBuilder {
    private readonly playlistSettings: IPlaylistSettings;
    private readonly singersConfig: ISingersConfig;
    private readonly musiciansConfig: IMusicianConfig;
    private readonly aerialConfig: IAerialConfig;
    private readonly playlistSong: IPlaylistSong;

    /**
     * @constructor
     * @param {IPlaylistBuilderInput} input - Parameters required to construct the playlist.
     */
    constructor(input: IPlaylistBuilderInput) {
        this.playlistSettings = input.playlistSettings;
        this.singersConfig = input.singersConfig;
        this.musiciansConfig = input.musiciansConfig;
        this.aerialConfig = input.aerialConfig;
        this.playlistSong = input.playlistSong;
    }

    /**
     * Builds a complete `IPlaylist` object containing all necessary information.
     * @returns {IPlaylist} A fully structured playlist object.
     */
    build(): IPlaylist {
        return {
            settings: this.playlistSettings,
            songList: Array.from(
                { length: this.playlistSettings.numberOfSongs },
                () => ({ ...this.playlistSong })
            ),
            performers: {
                singersConfig: this.singersConfig,
                musiciansConfig: this.musiciansConfig,
                aerialConfig: this.aerialConfig,
            }
        };
    }
}
